### ISSUE TITLE
NPE when clicking on new calendar

### ISSUE THREAD

**Issue by dschuermann** [etesync/android#10]
To reproduce:
1. create new calendar
2. directly afterwards click on the new calendar in the list below

```
04-25 14:30:17.946  24213    24213         AndroidRuntime  D  Shutting down VM
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  FATAL EXCEPTION: main
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  Process: com.etesync.syncadapter, PID: 24213
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.view.LayoutInflater.from(LayoutInflater.java:232)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:181)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:114)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at com.etesync.syncadapter.ui.journalviewer.ListEntriesFragment$EntriesListAdapter.<init>(ListEntriesFragment.java:91)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at com.etesync.syncadapter.ui.journalviewer.ListEntriesFragment$JournalFetch.onPostExecute(ListEntriesFragment.java:146)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at com.etesync.syncadapter.ui.journalviewer.ListEntriesFragment$JournalFetch.onPostExecute(ListEntriesFragment.java:136)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.os.AsyncTask.finish(AsyncTask.java:667)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.os.AsyncTask.-wrap1(AsyncTask.java)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:154)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:6121)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-25 14:30:17.946  24213    24213         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by dschuermann** [comment]
Forgot to add: After the crash it works, this happens only on newly created ones.

**Comment by tasn** [comment]
Darn. I'll take a look, thanks.

**Comment by tasn** [comment]
This should now be fixed by:
26c0a62dc4d67f58c9b7732f8170aa6f33260584
