### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by shawn1thompson** [etesync/android#195]
I'm receiving the following errors whenever a sync occurs on Android. Please let me know if any further info is needed. Thanks.

--- BEGIN DEBUG INFO ---
SYNCHRONIZATION INFO
Synchronization phase: applying remote entries
Account name: shawn10thompson
Authority: com.android.calendar
Debug activity source: class com.etesync.syncadapter.syncadapter.SyncNotification$NotificationHandlerActivity (Kotlin reflection is not available)

EXCEPTION:
at.bitfire.ical4android.InvalidCalendarException: Couldn't parse iCalendar
	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:84)
	at at.bitfire.ical4android.Event$Companion.eventsFromReader(Event.kt:85)
	at at.bitfire.ical4android.Event$Companion.eventsFromReader$default(Event.kt:84)
	at com.etesync.syncadapter.syncadapter.CalendarSyncManager.processItem(CalendarSyncManager.kt:89)
	at com.etesync.syncadapter.syncadapter.SyncManager.applyRemoteItems(SyncManager.kt:470)
	at com.etesync.syncadapter.syncadapter.SyncManager.performSync(SyncManager.kt:252)
	at com.etesync.syncadapter.syncadapter.CalendarsSyncAdapterService$SyncAdapter.onPerformSyncDo(CalendarsSyncAdapterService.kt:50)
	at com.etesync.syncadapter.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:117)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 15:Text cannot be parsed to a Duration
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:160)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:183)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:171)
	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:82)
	... 8 more
Caused by: j$.time.format.x: Text cannot be parsed to a Duration
	at j$.time.Duration.parse(:412)
	at net.fortuna.ical4j.model.TemporalAmountAdapter.parse(TemporalAmountAdapter.java:137)
	at net.fortuna.ical4j.model.property.Trigger.setValue(Trigger.java:270)
	at net.fortuna.ical4j.model.property.Trigger.<init>(Trigger.java:165)
	at net.fortuna.ical4j.model.property.Trigger$Factory.createProperty(Trigger.java:315)
	at net.fortuna.ical4j.model.PropertyBuilder.build(PropertyBuilder.java:48)
	at net.fortuna.ical4j.data.DefaultContentHandler.endProperty(DefaultContentHandler.java:123)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:294)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:226)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:213)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:429)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:211)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:429)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:211)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:116)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:182)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:151)
	... 11 more

SOFTWARE INFORMATION
EteSync version: 2.2.4 (20204) 
Installed from: com.google.android.packageinstaller
CONFIGURATION
Power saving disabled: yes
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: granted
org.dmfs.permission.WRITE_TASKS permission: granted
org.tasks.permission.READ_TASKS permission: denied
org.tasks.permission.WRITE_TASKS permission: denied
System-wide synchronization: automatically
Account: shawn10thompson
  Address book sync. interval: 240 min
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: 240 min
  Tasks.org    sync. interval: —
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
           Manage calendar colors: true
Address book account: Contacts (shawn10thompson L8)
  Main account: Account {name=shawn10thompson, type=com.etesync.syncadapter}
  URL: L8ZTDx4UFQi_np9YWKaHj0t-PAzmyjXu
  Sync automatically: true

SQLITE DUMP
android_metadata
	|  locale |

	|  en_US |
----------

settings

	|  setting | value |
----------

SERVICES DUMP

JOURNALS DUMP

SYSTEM INFORMATION
Android version: 9 (PPS29.118-15-11-16)
Device: Motorola moto g(6) (ali)

--- END DEBUG INFO ---

----------------------------------------------------------------------------------------------------------------

--- BEGIN DEBUG INFO ---
SYNCHRONIZATION INFO
Synchronization phase: applying remote entries
Account name: shawn10thompson
Authority: com.android.calendar
Debug activity source: class com.etesync.syncadapter.syncadapter.SyncNotification$NotificationHandlerActivity (Kotlin reflection is not available)

EXCEPTION:
at.bitfire.ical4android.InvalidCalendarException: Couldn't parse iCalendar
	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:84)
	at at.bitfire.ical4android.Event$Companion.eventsFromReader(Event.kt:85)
	at at.bitfire.ical4android.Event$Companion.eventsFromReader$default(Event.kt:84)
	at com.etesync.syncadapter.syncadapter.CalendarSyncManager.processItem(CalendarSyncManager.kt:89)
	at com.etesync.syncadapter.syncadapter.SyncManager.applyRemoteItems(SyncManager.kt:470)
	at com.etesync.syncadapter.syncadapter.SyncManager.performSync(SyncManager.kt:252)
	at com.etesync.syncadapter.syncadapter.CalendarsSyncAdapterService$SyncAdapter.onPerformSyncDo(CalendarsSyncAdapterService.kt:50)
	at com.etesync.syncadapter.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:117)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 13:Text cannot be parsed to a Duration
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:160)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:183)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:171)
	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:82)
	... 8 more
Caused by: j$.time.format.x: Text cannot be parsed to a Duration
	at j$.time.Duration.parse(:412)
	at net.fortuna.ical4j.model.TemporalAmountAdapter.parse(TemporalAmountAdapter.java:137)
	at net.fortuna.ical4j.model.property.Trigger.setValue(Trigger.java:270)
	at net.fortuna.ical4j.model.property.Trigger.<init>(Trigger.java:165)
	at net.fortuna.ical4j.model.property.Trigger$Factory.createProperty(Trigger.java:315)
	at net.fortuna.ical4j.model.PropertyBuilder.build(PropertyBuilder.java:48)
	at net.fortuna.ical4j.data.DefaultContentHandler.endProperty(DefaultContentHandler.java:123)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:294)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:226)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:213)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:429)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:211)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:429)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:211)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:116)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:182)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:151)
	... 11 more

SOFTWARE INFORMATION
EteSync version: 2.2.4 (20204) 
Installed from: com.google.android.packageinstaller
CONFIGURATION
Power saving disabled: yes
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: granted
org.dmfs.permission.WRITE_TASKS permission: granted
org.tasks.permission.READ_TASKS permission: denied
org.tasks.permission.WRITE_TASKS permission: denied
System-wide synchronization: automatically
Account: shawn10thompson
  Address book sync. interval: 240 min
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: 240 min
  Tasks.org    sync. interval: —
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
           Manage calendar colors: true
Address book account: Contacts (shawn10thompson L8)
  Main account: Account {name=shawn10thompson, type=com.etesync.syncadapter}
  URL: L8ZTDx4UFQi_np9YWKaHj0t-PAzmyjXu
  Sync automatically: true

SQLITE DUMP
android_metadata
	|  locale |

	|  en_US |
----------

settings

	|  setting | value |
----------

SERVICES DUMP

JOURNALS DUMP

SYSTEM INFORMATION
Android version: 9 (PPS29.118-15-11-16)
Device: Motorola moto g(6) (ali)

--- END DEBUG INFO ---

**Comment by shawn1thompson** [comment]
I fixed the issue by downloading the remote resource indicated in the debug file, finding the event in the calendar indicated, deleting the event, and recreating it.

**Comment by tasn** [comment]
Interesting that remote resources are causing troubles.
