### ISSUE TITLE
Some calendar not synchronizing (without error) on etesync 2.4.2 and Android 13

### ISSUE THREAD

**Issue by fdroiduser** [etesync/android#238]
Hi,
Since yesterday (when I upgraded to the latest version) my etesync app on my Android mobile phone is working (again), **but** one of the calendars is not synchronizing, and not showing any error/exception. The events log for this calendar in the Android app doesn't show any event since July 8th (even though I _did_ many local modifications since).

Versions:

    phone  : Galaxy S21 FE 5G
    OS     : Android 13
    Etesync: 2.4.2

The message says synchronization is a success, but one of the calendars actually remains unsynchronized. I'm still able to do modifications on other platforms (desktop), and I see these latter modifications on the web app; but the mobile phone calendar remains unsynchronized (both up and down).

Thanks!

**Comment by fdroiduser** [comment]
I enabled the verbose log, and looked into it. Here is the only error I can see:

```
(time) [com.etesync.syncadapter.HttpClient] <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

(time) [com.etesync.syncadapter.HttpClient] <-- END HTTP (170-byte body)
(time) [com.etesync.syncadapter.syncadapter.SyncNotification] HTTP Exception during sync
EXCEPTION com.etebase.client.exceptions.ServerErrorException: Server error
	at com.etebase.client.ItemManager.do_batch(Native Method)
	at com.etebase.client.ItemManager.batch(ItemManager.java:96)
	at com.etebase.client.ItemManager.batch(ItemManager.java:189)
	at com.etesync.syncadapter.syncadapter.SyncManager.pushItems(SyncManager.kt:593)
	at com.etesync.syncadapter.syncadapter.SyncManager.performSync(SyncManager.kt:235)
	at com.etesync.syncadapter.syncadapter.CalendarsSyncAdapterService$SyncAdapter.onPerformSyncDo(CalendarsSyncAdapterService.kt:50)
	at com.etesync.syncadapter.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:117)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)
```

I cannot see any `java.util.NoSuchElementException` (in contrast to [that other thread](https://github.com/etesync/android/issues/235)).

**Comment by barathrm** [comment]
> EXCEPTION com.etebase.client.exceptions.ServerErrorException: Server error

that's strange. I tried syncing directly with tasks.org, without the etesync app itself, and it also gave me a `Server error` message.

**Comment by barathrm** [comment]
Do you still have this issue @fdroiduser? The server was restarted recently and afterwards I haven't had this issue anymore.

**Comment by tripinside** [comment]
> 

Still not syncing with 2.4.3. 
2.3.0 worked by the past but no more available. Please need your help, I have also professional use.

Moto g7 plus
Official lineageos 20, A13
