### ISSUE TITLE
Calendar Syncing but Contacts Not

### ISSUE THREAD

**Issue by stevesbrain** [etesync/android#73]
Hey all, looks like my contacts aren't syncing for a new account (despite my calendar syncing). Verbose debug below of the relevant section (can censor and provide full log if needed):

```
2019-04-04 21:35:46 32527 [com.etesync.syncadapter.syncadapter.SyncManager] Syncing collection 6288ec9b086b0798d06b051117bcd3aff6faee05964a731dd53a30e31c5a8101 (version: 2)
2019-04-04 21:35:46 32527 [com.etesync.syncadapter.syncadapter.SyncManager] Sync phase: preparing synchronization
2019-04-04 21:35:46 32527 [com.etesync.syncadapter.syncadapter.SyncManager] I/O exception during sync, trying again later
EXCEPTION java.io.FileNotFoundException
        at at.bitfire.vcard4android.AndroidAddressBook.getSettings(AndroidAddressBook.kt:43)
        at com.etesync.syncadapter.syncadapter.ContactsSyncManager.prepare(ContactsSyncManager.kt:82)
        at com.etesync.syncadapter.syncadapter.SyncManager.performSync(SyncManager.kt:120)
        at com.etesync.syncadapter.syncadapter.ContactsSyncAdapterService.onPerformSync(ContactsSyncAdapterService.kt:60)
        at android.content.AbstractThreadedSyncAdapter.run(AbstractThreadedSyncAdapter.java:334)

2019-04-04 21:35:46 32527 [com.etesync.syncadapter.syncadapter.ContactsSyncAdapterService] Contacts sync complete
2019-04-04 21:35:50 2 [com.etesync.syncadapter.AccountUpdateService] Cleaning up orphaned accounts
```

I am trying to import 360 contacts when I do this. Wouldn't have expected that'd matter given I just did the same thing on a test docker image on my laptop - so docker image has changed machines, but nothing else is different :) Any insight would be great!

**Comment by stevesbrain** [comment]
Okay, so looks like the issue is I can't import contacts on a brand new (self hosted) account. I fixed by first creating (and then deleting) a contact entry, and then importing. Prior to doing this I first remove the account on the server and recreated it from scratch with a different encryption password, just to verify it wasn't something bizarre like that. I'll leave this open in case this is strange enough that you want more debug info, but otherwise feel free to close it of course :)

**Comment by tasn** [comment]
Weird. I've been staring at the code for the last 20 minutes trying to figure out what it may be.
I cleaned up some of the related code, and the actual place where it crashed, but I can't be sure it won't crash elsewhere.

Will push the fix later. Thanks for letting me know.

**Comment by stevesbrain** [comment]
No worries :)
