### ISSUE TITLE
EteSync v1.4.9 - Apk crashes when creating a task list

### ISSUE THREAD

**Issue by ammarraisafti** [etesync/android#80]
# Related information
- Repository: 

- Submitted issue: 

- GitHub accounts: https://github.com/ammarraisafti

# Actual behaviour
When I make a list of tasks, this application must run well. So, the ability to make a list of tasks can be done.

# Expected behaviour
The application suddenly stopped when I made a list of tasks. This problem continues even though I have tried to do it repeatedly.

# Step to reproduce
- Install and open the application. 

- Sign In using the account that you previously created. If you do not have an account, you must register first.

- Click on the account that you have created, then click on the three stack icon in the task list feature section.

- Select the "Create task list" feature, then fill in the display name and optional description.  Then click the "Save" icon at the top right.

- If it fails when saving, click the "Save" icon again.  Then you will find problems like I have experienced.

# Information
- Device: Nubia n2 lite
- Android version: 8.1.0
- Application version: 1.4.9

# Recording of the bug
https://youtu.be/Y8KYCPT3QK8

**Comment by tasn** [comment]
Your account looks broken. You don't have any calendars, address books or task lists. Are you sure it's even syncing correctly? I'd love to see the debug log it suggested to send to devs. That would better explain what's going on.

Thanks!

**Comment by ammarraisafti** [comment]
You can see it here.

<code>FATAL EXCEPTION: ModernAsyncTask #3
07-02 22:12:11.272 E/AndroidRuntime( 6933): Process: com.etesync.syncadapter, PID: 6933
07-02 22:12:11.272 E/AndroidRuntime( 6933): java.lang.RuntimeException: An error occurred while executing doInBackground()
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.lang.Thread.run(Thread.java:764)
07-02 22:12:11.272 E/AndroidRuntime( 6933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] com.etesync.syncadapter.model.JournalEntity.getEncryptedKey()' on a null object reference
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at com.etesync.syncadapter.ui.CreateCollectionFragment$CreateCollectionLoader.loadInBackground(CreateCollectionFragment.kt:121)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at com.etesync.syncadapter.ui.CreateCollectionFragment$CreateCollectionLoader.loadInBackground(CreateCollectionFragment.kt:79)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-02 22:12:11.272 E/AndroidRuntime( 6933):     ... 3 more</code>

**Comment by tasn** [comment]
Thanks.
What about my questions regarding your account looking broken? Why don't you have anything there?
Also, having looked at the log, I don't see how it's possible. For some reason you have the UID already set even though the collection doesn't exist, which shouldn't happen. I don't see any obvious reason in the code as to how/why it would happen.
