### ISSUE TITLE
The application still has some bugs

### ISSUE THREAD

**Issue by AssassinRain** [etesync/android#84]
Hello. I noticed some crashes in logs.  The corresponding commit version of code is  73f428a, and application version is 1.4.6. 
## 1.com.etesync.syncadapter.ui.AccountActivity
The exception trace is: 
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.etesync.syncadapter/com.etesync.syncadapter.ui.AccountActivity}: kotlin.UninitializedPropertyAccessException: lateinit property account has not been initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property account has not been initialized
	at com.etesync.syncadapter.ui.AccountActivity.onCreate(AccountActivity.kt:83)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### The command to trigger it is: adb shell am start -n com.etesync.syncadapter/com.etesync.syncadapter.ui.AccountActivity 

Because all these activities are exported ones, i.e., be exposed to outside, they may receive unfriendly commands and then lead to app crash.  After investigation, we found that the missing of null checkers causes those crashes. 
Please help to confirm whether they are true bugs. We believe that fixing these bugs will further improve the robustness of this app.

**Comment by tasn** [comment]
Nice catch, thanks!

Please the next time use a more descriptive title for the issue.
